import { ServiceItem } from "@/types/search";

export const mockResults: ServiceItem[] = [
  {
    title: "МРТ головного мозга с контрастированием",
    price: "28 000 ₸",
    oldPrice: "35 000 ₸",
    clinic: "Медицинский центр «Сункар»",
    address: "мкр. Нурсат, д. 23",
    metro: "мкр. Нурсат",
    distance: "1.2 км",
    rating: "4.8",
    reviewsCount: "142 отзыва",
    badge: "Мед услуги",
    lat: 42.3601,
    lng: 69.6105,
  },
  {
    title: "МРТ головного мозга (обзорное)",
    price: "18 000 ₸",
    oldPrice: "22 500 ₸",
    clinic: "Диагностический центр «Орда»",
    address: "ул. Бауыржана Момышулы, д. 14",
    metro: "Аль-Фарабийский р-н",
    distance: "0.8 км",
    rating: "4.9",
    reviewsCount: "89 отзывов",
    badge: "Мед услуги",
    lat: 42.3156,
    lng: 69.5976,
  },
  {
    title: "МРТ головного мозга + сосуды",
    price: "42 000 ₸",
    oldPrice: "5 000 ₸",
    clinic: "Клиника «Interteach»",
    address: "пр. Тауке хана, д. 45",
    metro: "Енбекшинский р-н",
    distance: "2.4 км",
    rating: "4.7",
    reviewsCount: "216 отзывов",
    badge: "Мед услуги",
    lat: 42.3195,
    lng: 69.6154,
  },
];
